name: Deploy React App to EC2

on:
  push:
    branches:
      - main   # Change branch if needed

jobs:
  build-deploy:
    runs-on: self-hosted   # your EC2 runner

    steps:
      # 1. Checkout code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Setup Node (via nvm)
      - name: Setup Node.js with nvm
        run: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 20
            nvm alias default 20
            nvm use 20
            node -v
            npm -v

      # 3. Install deps & build
      - name: Install & Build
        run: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 20
            npm ci
            npm run build

      # 4. Rsync build to /var/www/site1
      - name: Deploy to Nginx root
        run: |
          rsync -avz --delete dist/ /var/www/site1/
          sudo chown -R www-data:www-data /var/www/site1
          sudo chmod -R 755 /var/www/site1

      # 5. Reload Nginx
      - name: Reload Nginx
        run: |
          sudo systemctl reload nginx
